### ISSUE TITLE
Backend Issue

### ISSUE THREAD

**Issue by s21227c** [pjwstkIOprojekt/backend#28]
# Expected Behaviour
You're able to run backend following instructions in read.me
# Steps 
After following instructions and clicking "run" Build  is failed with exception.
# Description of problem
Exception is thrown by function seedUsers in class DatabaseSeeder and 126 line of code in KeycloakService.
In KeycloakService there is made list of roles based on keycloak server, and line 126 wants  to filtr exact role, but in keycloak list there isn't such a role(no dispatcher, only staff role).
@s20462

**Comment by s20462** [comment]
fixed closed
