### ISSUE TITLE
User endpoint issue

### ISSUE THREAD

**Issue by s18982** [pjwstkIOprojekt/backend#33]
User Id has string format (f. e. "07e9b697-4ccc-4261-89a8-2d6d502087f5").  

Endpoints of user take only int parameters.

Endpoints of user with int paramteres:
* GET /user/{id}
* PUT /user/{id}
* DELETE /user/{id}
* PUT /user/info/{id}
* POST /user/info/{id}

I cannot find any user because endpoints don't take string id or the user cannot be found by int id.
![01](https://user-images.githubusercontent.com/61829917/169115371-418cda9a-7cbf-42e8-9362-a08cabd69630.JPG)
![02](https://user-images.githubusercontent.com/61829917/169115381-7dfce269-34e0-4354-88e7-9d881da005d2.JPG)
![03](https://user-images.githubusercontent.com/61829917/169115383-fe04932e-fc42-45ff-a437-087df21594a1.JPG)
![04](https://user-images.githubusercontent.com/61829917/169115386-91ef1684-01dd-4e95-8dc7-bdd9a19e8138.JPG)

**Comment by s19068** [comment]
fixed in pr
